library(rjson)
source('questions.R', encoding='UTF-8')
download.file('https://docs.google.com/spreadsheets/d/1wQmcyGSXJIViYEXtYfXauo9aKfPrCbLYPhEA77v11ro/export?format=xlsx&id=1wQmcyGSXJIViYEXtYfXauo9aKfPrCbLYPhEA77v11ro', destfile="FragenFormat.xlsx", method="Curl")
xstr <- toJSON(list(questions=ELQuestions, atypes=ELATYPE, groups=ELGROUPS))
writeChar(xstr, file('questions.json'))
